### ISSUE TITLE
Add a package.json and drop node_modules

### ISSUE THREAD

**Issue by Ryuno-Ki** [ionicc/Github-organization-inviter#15]
This is a follow-up of #8.

In order to ease collaboration, the dependencies should be tracked in a `package.json`.
In that file you can also track meta information (like collaborators, link to issue page, version of the project etc).

If you worry about the dependencies, track also a `package-lock.json`.
If you really insist on consistencies over different machines, [choose yarn](https://yarnpkg.com/lang/en/docs/yarn-lock/).

**Comment by ionicc** [comment]
Absolutely correct, I was gonna drop the node_modules in the later commits. Since I'm maintaining the production deployment with this repo I didn't drop them as I didn't need to install the dependencies again with npm. 
We'll drop node_modules in the later commits along with the addition of package.json 😄
